name: candy_crush_clone
  description: A candy crush clone built with Flutter.
  publish_to: "none"

  environment:
    sdk: ">=3.0.0 <4.0.0"

  dependencies:
    flutter:
      sdk: flutter
    flutter_riverpod: ^2.6.1
    flutter_animate: ^4.5.0

  dev_dependencies:
    flutter_test:
      sdk: flutter

  flutter:
    uses-material-design: true